import json
import os

# Define the team name mapping in alphabetical order
team_name_mapping = {
    "Adrian": "Adrian Bulldogs",
    "Air Force": "Air Force Falcons",
    "Akron": "Akron Zips",
    "American": "American Eagles",
    "Army West Point": "Army West Point Black Knights",
    "Assumption": "Assumption Greyhounds",
    "Aurora": "Aurora Spartans",
    "Averett": "Averett Cougars",
    "Bellarmine": "Bellarmine Knights",
    "Belmont": "Belmont Bruins",
    "Belmont Abbey": "Belmont Abbey Crusaders",
    "Binghamton": "Binghamton BearCats",
    "Blackburn": "(no pairing found)",
    "Boston College": "Boston College Eagles",
    "Boston U.": "Boston Terriers",
    "Bowling Green": "Bowling Green Falcons",
    "Bradley": "Bradley Braves",
    "Brandeis": "(no pairing found)",
    "Brown": "Brown Bears",
    "Bryant": "Bryant Bulldogs",
    "Bucknell": "Bucknell Bison",
    "Butler": "Butler Bulldogs",
    "CSU Bakersfield": "CSU Bakersfield Roadrunners",
    "CSUN": "CSUN Matadors",
    "Cal Poly": "Cal Poly Mustangs",
    "Cal St. Fullerton": "Cal State Fullerton Titans",
    "California": "(no pairing found)",
    "California Baptist": "California Baptist Lancers",
    "Campbell": "Campbell Camels",
    "Canisius": "Canisius Golden Griffins",
    "Central Ark.": "Central Arkansas Bears",
    "Central Conn. St.": "(no pairing found)",
    "Charlotte": "Charlotte 49ers",
    "Chicago St.": "Chicago State Cougars",
    "Clemson": "Clemson Tigers",
    "Cleveland St.": "Cleveland State Vikings",
    "Coastal Carolina": "Coastal Carolina Chanticleers",
    "Col. of Charleston": "Charleston Cougars",
    "Colgate": "Colgate Raiders",
    "Columbia": "Columbia Lions",
    "Cornell": "Cornell Big Red",
    "Creighton": "Creighton Bluejays",
    "Dartmouth": "Dartmouth Big Green",
    "Davidson": "Davidson Wildcats",
    "Dayton": "Dayton Flyers",
    "DePaul": "DePaul Blue Demons",
    "Delaware": "Delaware Blue Hens",
    "Denver": "Denver Pioneers",
    "Detroit Mercy": "Detroit Mercy Titans",
    "Drake": "Drake Bulldogs",
    "Drexel": "Drexel Dragons",
    "Duke": "Duke Blue Devils",
    "Duquesne": "Duquesne Duke",
    "ETSU": "ETSU Buccaneers",
    "Eastern Ill.": "Eastern Illinois Panthers",
    "Elon": "Elon Phoenix",
    "Embry-Riddle (FL)": "Embry Riddle Eagles",
    "Evansville": "Evansville Purple Aces",
    "FDU": "Fairleigh Dickinson Knights",
    "FGCU": "FGCU Eagles",
    "FIU": "FIU Panthers",
    "Fairfield": "Fairfield Stags",
    "Fla. Atlantic": "FAU Owls",
    "Fordham": "Fordham Rams",
    "Fresno Pacific": "Fresno Pacific Sunbird",
    "Furman": "Furman Paladins",
    "Ga. Southern": "Georgia Southern Eagles",
    "Gardner-Webb": "Gardner-Webb Bulldogs",
    "George Mason": "George Mason Patriots",
    "George Washington": "George Washington Colonials",
    "Georgetown": "Georgetown Hoyas",
    "Georgia St.": "Georgia State Panthers",
    "Gonzaga": "Gonzaga Bulldogs",
    "Grand Canyon": "Grand Canyon Lopes",
    "Green Bay": "Green Bay Phoenix",
    "Greensboro": "Greensboro Pride",
    "Hampden-Sydney": "Hampden-Sydney Tigers",
    "Harvard": "Harvard Crimson",
    "High Point": "High Point Panthers",
    "Hofstra": "Hofstra Pride",
    "Holy Cross": "Holy Cross Crusaders",
    "Houston Christian": "(no pairing found)",
    "Howard": "Howard Bison",
    "IU Indy": "(no pairing found)",
    "Indiana": "Indiana Hoosiers",
    "Iona": "Iona Gaels",
    "Jacksonville": "Jacksonville Dolphins",
    "James Madison": "JMU Dukes",
    "Kansas City": "(no pairing found)",
    "Kentucky": "Kentucky Wildcats",
    "LIU": "LIU Sharks",
    "LMU (CA)": "LMU Lions",
    "La Salle": "La Salle Explorers",
    "Lafayette": "Lafayette Leopards",
    "Le Moyne": "Le Moyne Dolphins",
    "Lehigh": "Lehigh Mountain Hawks",
    "Liberty": "Liberty Flames",
    "Lindenwood": "Lindenwood Lions",
    "Lipscomb": "Lipscomb Bisons",
    "Longwood": "Longwood Lancers",
    "Louisville": "Louisville Cardinals",
    "Loyola Chicago": "Loyola Chicago Ramblers",
    "Loyola Maryland": "Loyola Greyhounds",
    "Manhattan": "Manhattan Jaspers",
    "Marist": "Marist Red Foxes",
    "Marquette": "Marquette Golden Eagles",
    "Marshall": "Marshall Thundering Herd",
    "Mary Baldwin": "Mary Baldwin",
    "Maryland": "Maryland College Park Terrapins",
    "Massachusetts": "UMass Minutemen",
    "Memphis": "Memphis Tigers",
    "Mercer": "Mercer Bears",
    "Merrimack": "Merrimack Warriors",
    "Michigan": "Michigan Wolverines",
    "Michigan St.": "Michigan State Spartans",
    "Milwaukee": "Milwaukee Panthers",
    "Missouri St.": "Missouri State Bears",
    "Monmouth": "Monmouth Hawks",
    "Mount St. Mary's": "Mount St. Mary's Mountaineers",
    "NC State": "NC State Wolfpack",
    "NIU": "Northern Illinois Huskies",
    "NJIT": "NJIT Highlanders",
    "Navy": "Navy Midshipmen",
    "New Hampshire": "New Hampshire Wildcats",
    "Niagara": "Niagara Purple Eagles",
    "North Carolina": "North Carolina Heels",
    "North Florida": "North Florida Ospreyes",
    "Northeastern": "Northeastern Huskies",
    "Northern Ky.": "NKU Norse",
    "Northwestern": "Northwestern Wildcats",
    "Notre Dame": "Notre Dame Fighting Irish",
    "Oakland": "Oakland Golden Grizzlies",
    "Oberlin": "Oberlin Yeomen",
    "Ohio St.": "Ohio State Buckeyes",
    "Old Dominion": "Old Dominion Monarchs",
    "Omaha": "Omaha Mavericks",
    "Oral Roberts": "Oral Roberts Golden Eagles",
    "Oregon St.": "Oregon State Beavers",
    "Pacific": "Pacific Tigers",
    "Penn": "Penn Quakers",
    "Penn St.": "Penn State Nittany Lion",
    "Pittsburgh": "Pittsburgh Panthers",
    "Portland": "Portland Pilots",
    "Presbyterian": "Presbyterian BlueHose",
    "Princeton": "Princeton Tigers",
    "Providence": "Providence Friars",
    "Purdue Fort Wayne": "IPFW Mastodons",
    "Queens (NC)": "Queens Royals",
    "Quinnipiac": "Quinnipiac Bobcats",
    "Radford": "Radford Highlanders",
    "Rhode Island": "Rhode Island Rhody",
    "Rider": "Rider Broncs",
    "Robert Morris": "Robert Morris Colonials",
    "Rutgers": "Rutgers Scarlet Knights",
    "SIUE": "SIUE Cougars",
    "SMU": "SMU Mustangs",
    "SUNY Maritime": "(no pairing found)",
    "Sacramento St.": "Sacramento State Hornets",
    "Sacred Heart": "(no pairing found)",
    "Saint Francis": "(no pairing found)",
    "Saint Joseph's": "Saint Joseph's Hawks",
    "Saint Louis": "Saint Louis Billikens",
    "Saint Mary's (CA)": "St. Mary's College of CA Gaels",
    "Saint Peter's": "Saint Peter's Peacocks",
    "San Diego": "San Diego Toreros",
    "San Diego St.": "San Diego State Aztecs",
    "San Francisco": "San Francisco Dons",
    "San Jose St.": "San Jose State Spartans",
    "Santa Clara": "Santa Clara Broncos",
    "Seattle U": "Seattle Redhawks",
    "Seton Hall": "Seton Hall Pirates",
    "Siena": "Siena Saints",
    "South Carolina": "South Carolina Gamecocks",
    "South Fla.": "USF Bulls",
    "Southern Ind.": "Southern Indiana Screaming Eagles",
    "Southern Wesleyan": "Southern Wesleyan Warriors",
    "Southwest Baptist": "Southwest Baptist Bearcats",
    "St. Bonaventure": "St. Bonaventure Bonnies",
    "St. John's (NY)": "St John's Red Storm",
    "St. Joseph's (L.I.)": "Saint Joseph's Golden Eagles",
    "St. Thomas (MN)": "St. Thomas Tommies",
    "Stanford": "Stanford Cardinal",
    "Stetson": "Stetson Hatters",
    "Stonehill": "Stonehill College Skyhawks",
    "Stony Brook": "Stony Brook Seawolves",
    "Suffolk": "Suffolk Rams",
    "Syracuse": "Syracuse Orange",
    "Temple": "Temple Owls",
    "Trine": "Trine Thunder",
    "Trinity (TX)": "Trinity Tigers",
    "Tulsa": "Tulsa Hurricane",
    "UAB": "UAB Blazers",
    "UAlbany": "Albany Great Danes",
    "UC Davis": "UC Davis Aggies",
    "UC Irvine": "UC Irvine Anteaters",
    "UC Riverside": "UC Riverside Highlanders",
    "UCLA": "UCLA Bruins",
    "UMass Lowell": "UMass Lowell River Hawks",
    "UMKC": "UMKC Kangaroos",
    "UNC Asheville": "UNC Asheville Bulldogs",
    "UNC Greensboro": "UNC Greensboro Spartans",
    "UNC Wilmington": "UNC Wilmington Seahawks",
    "USC": "USC Trojans",
    "UTEP": "UTEP Miners",
    "Utah": "Utah Utes",
    "Utah Valley": "Utah Valley Wolverines",
    "Valparaiso": "Valparaiso Crusaders",
    "Vanderbilt": "Vanderbilt Commodores",
    "Vermont": "Vermont Catamounts",
    "Villanova": "Villanova Wildcats",
    "Virginia": "Virginia Cavaliers",
    "Virginia Tech": "Virginia Tech Hokies",
    "Wagner": "Wagner Seahawks",
    "Wake Forest": "Wake Forest Demon Deacons",
    "Washington": "Washington Huskies",
    "Washington St.": "Washington State Cougars",
    "West Virginia": "West Virginia Mountaineers",
    "Wichita St.": "Wichita State Shockers",
    "Wisconsin": "Wisconsin Badgers",
    "Wright St.": "Wright State Raiders",
    "Yale": "Yale Bulldogs"
}

# Path to the directory containing JSON files
games_directory = 'games'

# Loop through all JSON files in the directory
for filename in os.listdir(games_directory):
    if filename.endswith('.json'):
        file_path = os.path.join(games_directory, filename)

        # Load the JSON data
        with open(file_path, 'r') as file:
            games = json.load(file)

        # Update team names based on the mapping
        for game in games:
            home_team = game.get("home_team")
            away_team = game.get("away_team")
            if home_team in team_name_mapping:
                game["home_team"] = team_name_mapping[home_team]
            if away_team in team_name_mapping:
                game["away_team"] = team_name_mapping[away_team]

        # Save the updated JSON data back to the file
        with open(file_path, 'w') as file:
            json.dump(games, file, indent=4)

print("Team names updated successfully.")
